### ISSUE TITLE
When im using 3.0 DARK and 2.0 colors the xtentions page is broken

### ISSUE THREAD

**Issue by YOYITsM3M8** [infinitytec/3.Dark#10]

**Comment by infinitytec** [comment]
I'll look into it. Thanks for letting me know!

**Comment by infinitytec** [comment]
Do you have a screenshot of the issue?

**Comment by infinitytec** [comment]
@YOYITM3M8 I have made some updates to the userscript. If you could make sure you are on the latest version and see if it is still causing a problem that would be helpful!

**Comment by infinitytec** [comment]
Closing as I believe this was resolved a while ago.
